services:
  nextcloud-server:
    image: nextcloud:latest
    depends_on: 
      - nextcloud-db
      - nextcloud-aio-redis
    container_name: nextcloud
    shm_size: 256mb
    links:
     - nextcloud-aio-redis
    ports:
      - ${WEB_PORT}
    environment:
      - NC_DOMAIN=${NC_DOMAIN}
      - APACHE_PORT=${APACHE_PORT}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
    volumes:
      - ./nextcloud:/var/www/html
      - ./apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      # Socket
      - /var/run/clamav/:/var/run/clamav/
    restart: unless-stopped
    networks:
      - nextcloud

  nextcloud-db:
    image: mysql:8
    container_name: nextcloud_db
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_HOST}
    stop_grace_period: 1800s
    restart: unless-stopped
    shm_size: 256mb 
    networks:
      - nextcloud

  nextcloud-aio-redis:
    image: nextcloud/aio-redis:latest
    container_name: nextcloud-aio-redis
    init: true
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis:/data:rw
    restart: unless-stopped
    networks:
      - nextcloud
    read_only: true

  nextcloud-cron:
    image: nextcloud:latest
    container_name: nextcloud-cron
    restart: unless-stopped
    shm_size: 256mb    
    env_file:
      - .env
    volumes:
      - ./nextcloud:/var/www/html
      - ./apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-server

  clamav:
    image: "clamav/clamav:stable_base"
    container_name: "clamav"
    volumes:
      # Socket
      - /var/run/clamav/:/var/run/clamav/
      # Virus DB
      - /var/docker/clamav/virus_db/:/var/lib/clamav/
    ports:
      - 3310:3310
      - 7357:7357
    restart: unless-stopped

#volumes:
#  nextcloud_aio_apache:
#    name: nextcloud_aio_apache
#  nextcloud_aio_database:
#    name: nextcloud_aio_database
#  nextcloud_aio_database_dump:
#    name: nextcloud_aio_database_dump
#  nextcloud_aio_nextcloud:
#    name: nextcloud_aio_nextcloud
#  nextcloud_aio_nextcloud_data:
#    name: nextcloud_aio_nextcloud_data
#  nextcloud_aio_redis:
#    name: nextcloud_aio_redis

networks:
  nextcloud:
    name: nextcloud

