version: '3.8'

services:
  coturn:
    image: docker.io/coturn/coturn:latest
    container_name: coturn
    restart: unless-stopped
    network_mode: host
    volumes:
      - "./conf:/etc/turnserver.conf"
    tmpfs:
      - "/var/lib/coturn"
